logger:
  name: ITester
  level: DEBUG
  filename: ITester.log
  file: os.path.join(os.path.dirname(__file__), 'logger.log')
#  level: INFO
  format: '%(filename)s-%(lineno)d-%(asctime)s-%(levelname)s-%(message)s'

mongDB:
  host: 192.168.7.72
  port: 27017
  db_name: fastbull_universal_test
  username: fastbull
  password: IOE*2EW#OIWddOPcDWE
