# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtGui, QtWidgets, uic


class Ui_widget(object):
    # def __init__(self):
    #     # 从 UI 定义中动态 创建一个相应的窗口对象
    #     # 注意：里面的控件对象也成为窗口对象的属性了
    #     # 比如 self.ui.button , self.ui.textEdit
    #     # self.ui = QUiLoader().load('main.ui')
    #     # 从文件中加载UI定义
    #

    def setupUi(self, widget):
        self.ui = uic.loadUi("login.ui")
        self.ui.setObjectName("widget")
        widget.resize(800, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(widget.sizePolicy().hasHeightForWidth())
        widget.setSizePolicy(sizePolicy)
        widget.setMinimumSize(QtCore.QSize(500, 500))
        widget.setMaximumSize(QtCore.QSize(1000, 1000))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/Administrator/Pictures/百万医疗险和重疾险的区别.webp"), QtGui.QIcon.Normal,
                       QtGui.QIcon.Off)
        widget.setWindowIcon(icon)
        self.widget = QtWidgets.QWidget(widget)
        self.widget.resize(400, 100)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(100, 90))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("logo.ico"))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(22)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.widget1 = QtWidgets.QWidget(widget)
        self.widget1.setGeometry(QtCore.QRect(250, 250, 133, 100))
        self.widget1.setObjectName("widget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.edt_username = QtWidgets.QLineEdit(self.widget1)
        self.edt_username.setObjectName("edt_username")
        self.verticalLayout.addWidget(self.edt_username)
        self.edt_pwd = QtWidgets.QLineEdit(self.widget1)
        self.edt_pwd.setObjectName("edt_pwd")
        self.verticalLayout.addWidget(self.edt_pwd)
        self.btn_login = QtWidgets.QPushButton(self.widget1)
        self.btn_login.setObjectName("btn_login")
        self.verticalLayout.addWidget(self.btn_login)

        self.retranslateUi(widget)
        QtCore.QMetaObject.connectSlotsByName(widget)

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        self.ui.setWindowTitle(_translate("widget", "登录"))
        self.label_2.setText(_translate("widget", "黑羽学院数据处理工具"))
        self.edt_username.setPlaceholderText(_translate("widget", "用户名"))
        self.edt_pwd.setPlaceholderText(_translate("widget", "密码"))
        self.btn_login.setText(_translate("widget", "登录"))


if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    QObject = QtWidgets.QWidget()
    ui = Ui_widget()
    ui.setupUi(QObject)
    QObject.show()
    sys.exit(app.exec_())
