# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '读者书库.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtGui, QtWidgets, uic


# import uic
from PyQt5.QtWidgets import QApplication, QMainWindow


class Ui_RCQ(object):
    def setupUi(self, RCQ):
        self.ui = uic.loadUi("读者书库.ui", RCQ)

        RCQ.setObjectName("RCQ")
        RCQ.resize(400, 500)
        self.gridLayout_4 = QtWidgets.QGridLayout(RCQ)
        self.gridLayout_4.setObjectName("gridLayout_4")

        # 设置‘抓取设置’
        self.groupBox = QtWidgets.QGroupBox(RCQ)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)

        self.edt_qishu = QtWidgets.QLineEdit(self.groupBox)
        self.edt_qishu.setObjectName("edt_qishu")
        self.edt_qishu.setPlaceholderText('请输入期数')
        self.horizontalLayout.addWidget(self.edt_qishu)

        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")

        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.edt_savePath = QtWidgets.QLineEdit(self.groupBox)
        self.edt_savePath.setObjectName("edt_savePath")
        self.horizontalLayout_2.addWidget(self.edt_savePath)

        self.btn_select = QtWidgets.QPushButton(self.groupBox)
        self.btn_select.setObjectName("btn_select")
        self.horizontalLayout_2.addWidget(self.btn_select)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        #确定按钮
        self.btn_comfirm = QtWidgets.QPushButton(self.groupBox)
        self.btn_comfirm.setObjectName("btn_comfirm")

        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox, 0, 0, 1, 1)

        self.tab_showResult = QtWidgets.QTabWidget(RCQ)
        self.tab_showResult.setObjectName("tab_showResult")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tableWidget = QtWidgets.QTableWidget(self.tab)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.gridLayout_3.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.tab_showResult.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.listWidget = QtWidgets.QListWidget(self.tab_2)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout_2.addWidget(self.listWidget, 0, 0, 1, 1)
        self.tab_showResult.addTab(self.tab_2, "")
        self.gridLayout_4.addWidget(self.tab_showResult, 1, 0, 1, 1)

        self.retranslateUi(RCQ)
        self.tab_showResult.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(RCQ)

    def retranslateUi(self, RCQ):
        _translate = QtCore.QCoreApplication.translate
        RCQ.setWindowTitle(_translate("RCQ", "RCQ读者书库"))
        self.groupBox.setTitle(_translate("RCQ", "抓取设置"))
        self.label.setText(_translate("RCQ", "请选择抓取期数："))
        self.edt_qishu.setPlaceholderText(_translate("RCQ", "请输入期数"))
        self.label_3.setText(_translate("RCQ", "（期数范围为01--24）"))
        self.label_2.setText(_translate("RCQ", "请选择保存路径："))
        self.edt_savePath.setPlaceholderText(_translate("RCQ", "请输入保存路径"))
        self.btn_select.setText(_translate("RCQ", "选择"))
        self.btn_comfirm.setText(_translate("RCQ", "确定"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("RCQ", "期数"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("RCQ", "名称"))
        self.tab_showResult.setTabText(self.tab_showResult.indexOf(self.tab), _translate("RCQ", "按期数显示"))
        self.tab_showResult.setTabText(self.tab_showResult.indexOf(self.tab_2), _translate("RCQ", "按名称显示"))

if __name__ == '__main__':
    app=QtWidgets.QApplication(sys.argv)
    QObject=QtWidgets.QWidget()
    ui=Ui_RCQ()
    ui.setupUi(QObject)
    QObject.show()
    sys.exit(app.exec_())
    # app = QtWidgets.QApplication([])
    # RCQ = QtWidgets.QMainWindow()
    # ui = Ui_RCQ()
    # ui.setupUi(RCQ)
    # RCQ.show()
    # app.exec_()